# Generated by Django 5.1.3 on 2024-11-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LW', 'Low'), ('AR', 'Average'), ('HG', 'High')], default='LW', max_length=2),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('GR', 'Grooming'), ('IP', 'In Progress'), ('DV', 'Dev'), ('DN', 'Done')], default='GR', max_length=2),
        ),
    ]
