# Generated by Django 5.1.3 on 2024-11-06 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to=None)),
                ('role', models.CharField(choices=[('IN', 'Intern'), ('FR', 'Frontend'), ('BK', 'Backend'), ('DO', 'Devops'), ('PM', 'Project_Manager'), ('AN', 'Analyst'), ('DS', 'Designer')], default='IN', max_length=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
    ]
