# Generated by Django 5.1.3 on 2024-11-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='project',
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(to='main.project'),
        ),
    ]
