# Generated by Django 5.1.3 on 2024-11-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment'),
        ('users', '0002_remove_user_project_user_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='main.project'),
        ),
    ]
