# Generated by Django 5.1.3 on 2024-11-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usable_password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
